// 使用隔离测试服务器，不连接作者的正式数据。
const { chromium } = require('playwright')
const assert = require('node:assert/strict')

;(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
    await page.goto(process.env.STORY_TEST_URL || 'http://127.0.0.1:8012')
    await page.locator('.story-builder-empty, .story-builder-page').waitFor()
    // 每次都用新会话，保证本脚本可以重复运行。
    await page.request.post(new URL('/api/story-builder/sessions', page.url()).href, { data: { project_id: 'novel_project' } })
    await page.reload()
    await page.locator('.story-builder-page').waitFor()
    await page.locator('.builder-option').first().waitFor()
    for (let n = 0; n < 10; n++) {
      await page.locator('.builder-option:not([disabled])').first().click()
      const next = page.getByRole('button', { name: n === 9 ? '完成构筑' : '确认并继续', exact: true })
      await next.click()
      if (n < 9) await page.locator('.story-builder-version').filter({ hasText: `选择版本 ${n + 1}` }).waitFor()
    }
    await page.getByRole('heading', { name: '设定已完成，开始你的故事' }).waitFor()
    assert.equal(await page.locator('.builder-config-details').first().getAttribute('open'), null)
    await page.getByRole('button', { name: '确认故事蓝图', exact: true }).click()
    await page.getByRole('button', { name: '开始 / 继续旅程' }).click()
    await page.locator('.adventure-choices button').first().click()
    await page.locator('.adventure-choices button').first().waitFor()
    await page.reload()
    await page.getByRole('button', { name: '开始 / 继续旅程' }).click()
    await page.locator('.adventure-choices button').first().click()
    await page.locator('.adventure-choices button').first().click()
    await page.getByRole('heading', { name: '本段旅程结束' }).waitFor()
    await page.locator('.adventure-panel').screenshot({ path: 'workspace/adventure-desktop.png' })
    await page.setViewportSize({ width: 390, height: 844 })
    await page.locator('.adventure-panel').screenshot({ path: 'workspace/adventure-mobile.png' })
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false)
    assert.equal(await page.locator('.adventure-panel article').count(), 3)
    await page.getByRole('button', { name: '从第 1 次选择前另开路线', exact: true }).click()
    // 分支从第 1 次选择前重放：这里选择收集物资，验证分支状态与主线互不影响。
    await page.locator('.adventure-choices button').first().waitFor()
    const branchChoices = await page.locator('.adventure-choices button').count()
    assert.ok(branchChoices >= 1, '分支起点应有可选行动，实际 ' + branchChoices)
    await page.locator('.adventure-choices button').nth(branchChoices - 1).click()
    // 分支从“已经帮过同行者”的状态重放：1 - 1 + 2 = 2，与主线各自独立。
    await page.locator('.adventure-stats').getByText('补给 2', { exact: true }).waitFor()
    await page.locator('.adventure-route-select select').selectOption('main')
    await page.getByRole('heading', { name: '本段旅程结束' }).waitFor()
    await page.locator('.adventure-stats').getByText('补给 1', { exact: true }).waitFor()
    await page.reload()
    await page.getByRole('button', { name: '开始 / 继续旅程' }).click()
    await page.locator('.adventure-route-select option').nth(1).waitFor({ state: 'attached' })
    assert.equal(await page.locator('.adventure-route-select option').count(), 2)
    const storyId = await page.getByRole('combobox', { name: '已保存故事' }).inputValue()
    await page.getByRole('button', { name: '新建故事', exact: true }).click()
    await page.getByRole('heading', { name: '阅读体验', exact: true }).waitFor()
    assert.notEqual(await page.getByRole('combobox', { name: '已保存故事' }).inputValue(), storyId)
    await page.getByRole('combobox', { name: '已保存故事' }).selectOption(storyId)
    await page.getByRole('heading', { name: '设定已完成，开始你的故事' }).waitFor()
    await page.reload()
    await page.getByRole('heading', { name: '设定已完成，开始你的故事' }).waitFor()
    assert.equal(await page.getByRole('combobox', { name: '已保存故事' }).inputValue(), storyId)
    await page.getByRole('combobox', { name: '新故事起点' }).selectOption('worldview')
    await page.getByRole('button', { name: '新建故事', exact: true }).click()
    await page.locator('.builder-option').filter({ hasText: '多境修仙世界' }).click()
    await page.getByRole('button', { name: '确认并继续', exact: true }).click()
    await page.getByRole('heading', { name: '阅读体验', exact: true }).waitFor()
    await page.getByRole('combobox', { name: '新故事起点' }).selectOption('protagonist')
    await page.getByRole('button', { name: '新建故事', exact: true }).click()
    await page.getByRole('heading', { name: '主角原型', exact: true }).waitFor()
    await page.locator('.builder-custom-input textarea').fill('寻找家书的渡口记录员')
    await page.getByRole('button', { name: '确认并继续', exact: true }).click()
    await page.getByRole('heading', { name: '阅读体验', exact: true }).waitFor()
    await page.reload()
    await page.getByRole('heading', { name: '阅读体验', exact: true }).waitFor()
    assert.ok((await page.locator('main').textContent()).includes('寻找家书的渡口记录员'))
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false)
    console.log('通过：十步完成、确认蓝图、三关分支、刷新恢复、手机宽度。')
  } finally { await browser.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
