// 只连接隔离测试服务；不操作正式作者存档。
const { chromium, request } = require('playwright')
const assert = require('node:assert/strict')
;(async () => {
  const base = process.env.STORY_TEST_URL || 'http://127.0.0.1:8012'
  const http = await request.newContext({ baseURL: base })
  const created = await (await http.post('/api/story-builder/sessions', { data: { project_id: 'novel_project' } })).json()
  const url = '/api/story-builder/sessions/' + created.session.session_id
  const catalog = await (await http.get('/api/story-builder/catalogs')).json()
  for (const [version, step] of catalog.steps.entries()) {
    const rec = await (await http.post(url + '/recommendations', { data: { step: step.step } })).json()
    const saved = await http.post(url + '/selections', { data: { step: step.step, option_ids: [rec.recommendation.recommendations[0].option_id], expected_selection_version: version } })
    assert.equal(saved.status(), 200)
  }
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
    await page.goto(base)
    await page.locator('.design-expansion > summary').click()
    const choose = async (title, option) => {
      const node = page.locator('.design-node').filter({ has: page.locator('summary b', { hasText: title }) }).first()
      if (await node.getAttribute('open') === null) await node.locator(':scope > summary').click()
      await node.getByRole('radio', { name: option, exact: true }).click()
      await node.locator(':scope > summary span').filter({ hasText: option }).waitFor()
    }
    await choose('社会秩序', '能源配额城')
    await choose('生活地域', '冷却塔聚落')
    await choose('社会位置', '被配额约束的学徒')
    await choose('当前危机', '维生设施即将停摆')
    await page.reload()
    await page.locator('.design-expansion > summary').click()
    assert.equal(await page.locator('.design-node > summary span').filter({ hasText: '冷却塔聚落' }).count(), 1)
    await choose('社会位置', '承担生计的小店主')
    await page.locator('.design-node').filter({ hasText: '当前危机' }).getByText('待复核', { exact: true }).waitFor()
    await choose('当前危机', '维生设施即将停摆')
    await page.getByRole('tab', { name: /^主角/ }).click()
    await choose('主角 · 关键经历', '曾经救援失败')
    await choose('主角 · 欲望与恐惧', '保住身边的人')
    await choose('主角 · 压力反应', '先确认退路')
    await page.getByRole('tab', { name: /^开篇/ }).click()
    await page.getByRole('button', { name: '查看全部 12 个方向' }).click()
    await choose('开篇 · 第一个故事问题', '悬案发现')
    await choose('结局方向', '阶段完成，未来开放')
    await page.getByRole('tab', { name: /^定位与主题/ }).click()
    await choose('故事规模', '长篇连载')
    await choose('核心价值冲突', '真相与安稳')
    await page.getByRole('tab', { name: /^叙事方式/ }).click()
    await choose('叙述视角', '第一人称限知')
    await choose('叙述顺序', '结果前置再回溯')
    await page.getByRole('tab', { name: /^世界规则/ }).click()
    await choose('世界 · 共同约束', '获得必有交换')
    await page.getByRole('tab', { name: /^势力与场所/ }).click()
    await choose('场所 · 通行条件', '有开放时段')
    await page.getByRole('tab', { name: /^能力与资源/ }).click()
    await choose('成长 · 获得途径', '观察与练习')
    await choose('成长 · 使用边界', '消耗材料或工具')
    await page.getByRole('tab', { name: /^同伴与对手/ }).click()
    await choose('同伴 · 关系来由', '共同经历过失败')
    await choose('同伴 · 自己的目标', '修复旧日损失')
    await choose('同伴 · 合作边界', '必须自己决定风险')
    await choose('关系 · 当前摩擦', '目标相同，方法不同')
    await page.getByRole('tab', { name: /^开篇/ }).click()
    await choose('信息 · 揭露方式', '每次回答推进一层')
    await page.setViewportSize({ width: 390, height: 844 })
    await page.locator('.design-tree').screenshot({ path: 'workspace/design-tree-mobile.png' })
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
    const bp = await (await http.post(url + '/compile-blueprint')).json()
    assert.equal(bp.blueprint.design_choices.opening_pattern.option_id, 'opening_mystery')
    assert.equal(bp.blueprint.unresolved_conflicts.length, 0)
    await http.post('/api/story-builder/blueprints/' + bp.blueprint.blueprint_id + '/confirm', { data: { version: bp.blueprint.version } })
    await page.reload()
    await page.getByRole('button', { name: '开始 / 继续旅程' }).click()
    await page.getByRole('heading', { name: '对不上的记录', exact: true }).waitFor()
    await page.getByRole('button', { name: /先帮同行者/ }).click()
    await page.getByRole('button', { name: /请同行者协助/ }).click()
    await page.getByRole('button', { name: /用已有帮助或证据/ }).click()
    await page.getByRole('heading', { name: '本段旅程结束' }).waitFor()
    assert.match(await page.locator('.adventure-prose').innerText(), /临时修复设施/)
    await page.getByRole('button', { name: /先补给并兑现/ }).click()
    await page.getByRole('button', { name: /先用一份物资兑现约定/ }).click()
    await page.getByRole('button', { name: /去找实际交接人核对回执/ }).click()
    await page.getByRole('button', { name: /到留档处核对/ }).click()
    await page.getByRole('button', { name: /公开核实过的调拨证据/ }).click()
    await page.getByRole('heading', { name: '篇章已收束', exact: true }).waitFor()
    assert.equal(await page.locator('.adventure-choices button').count(), 0)
    await page.locator('.adventure-panel').screenshot({ path: 'workspace/followup-mobile.png' })
    await page.getByRole('button', { name: '用当前路线整合大纲', exact: true }).click()
    await page.getByRole('button', { name: '确认全书主线', exact: true }).click()
    for (const level of ['卷纲', '篇章纲', '详细章纲']) {
      await page.getByRole('button', { name: '生成' + level, exact: true }).click()
      await page.getByRole('button', { name: '确认' + level, exact: true }).click()
    }
    const chapter = page.locator('.builder-outline-level').filter({ has: page.getByRole('heading', { name: '详细章纲', exact: true }) })
    assert.equal(await chapter.locator('.builder-outline-items > details').count(), 8)
    await chapter.locator('.builder-outline-items > details').first().locator(':scope > summary').click()
    await chapter.getByRole('button', { name: '编辑此条' }).first().click()
    await chapter.getByRole('textbox', { name: '标题', exact: true }).fill('读者可以看懂的第一章')
    await chapter.getByRole('button', { name: '保存为新版本' }).click()
    await chapter.getByRole('button', { name: '确认详细章纲' }).click()
    const downloadPromise = page.waitForEvent('download')
    await chapter.getByRole('button', { name: '导出详细章纲' }).click()
    const download = await downloadPromise
    const content = require('node:fs').readFileSync(await download.path(), 'utf8')
    assert.match(content, /读者可以看懂的第一章/)
    assert.match(content, /状态：已确认/)
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
    console.log('通过：背景四层、刷新恢复、定向复核、角色推荐、开篇选择、手机布局。')
  } finally { await browser.close(); await http.dispose() }
})().catch(error => { console.error(error); process.exitCode = 1 })
